on:
  push:
    branches:
    - master
    - ci-test
  pull_request:
    branches:
    - master

name: Run Tox tests

jobs:
  tox_test:
    name: Tox test
    steps:
    - uses: actions/checkout@v2
    - name: Run Tox tests
      id: test
      uses: fedora-python/tox-github-action@master
      with:
        tox_env: ${{ matrix.tox_env }}
        dnf_install: /usr/bin/make
    strategy:
      matrix:
        tox_env: [
            py27-c90, py34-c90, py35-c90, py36-c90,
            py27-c99, py34-c90, py35-c99, py36-c99, py37-c99, py38-c99, py39-c99, py310-c99,
            py27-c90, py34-c90, py35-cpp, py36-cpp, py37-cpp, py38-cpp, py39-cpp, py310-cpp,
        ]

    # Use GitHub's Linux Docker host
    runs-on: ubuntu-latest
